### ISSUE TITLE
Program Level Resources

### ISSUE THREAD

**Issue by beingben** [trailliferesources/trailliferesources#1]
Will you include resources based on program level Woodlands Trail (Fox, Hawk, Mountain Lion), Navigator, Adventurer, Guidon?

If so -- will badge helps need to be sorted into Woodlands Trail, Nav Only, Nav/Ad Combined, and Adventurer Only buckets?

**Comment by beingben** [comment]
I'm happy to fork an do the PR if you would like. I just want to know what you prefer with organizing the info.

**Comment by paschott** [comment]
Man - hadn't even gotten that far. I don't think I've even got a website actually working yet.  Organization is still up in the air a bit - generally by "Overall", then by program. For WT, probably also by Fox/Hawk/ML.  But at this point, I'm wondering if we need to hold off a bit for the Nav/Adv area until we get the new handbooks/program details later this year.

Also still trying to make sure this doesn't give us fits w/ the Home Office.  As such, I don't want to store actual requirements and copyrighted materials, but thinks like "Ropework ... what is an H-frame" could be valid.  I get that the Home Office doesn't want to handle things officially - that takes staff to edit, update, and so on.  But I've heard the "I miss the badge handbook" comment from several over time and I agree some sort of "helps" would be useful.

**Comment by beingben** [comment]
So is this going to serve as general content to show/demonstrate how to complete badge/branch requirements? In woodlands trail is that different from [Heritage Flag Etiquette and History Lesson Plan](https://www.traillifeconnect.com/getdoc/wmeuxp4fa2hr) and [Flag Etiquette and History Helps](https://www.traillifeconnect.com/getdoc/ii7hgfqunxma).

It seems like you could link to the plans (this will require some maintenance as materials are released over time -- but that can be automated to some degree as well). Then have supporting materials and links for each lesson plan?

**Comment by paschott** [comment]
Just overall badge helps - maybe things that leaders found useful that aren't in the Plan/Helps documents. Definitely intended more for Nav/Adv where any sort of helps/resources/plans are up to the individual to find and use, but also general stuff like Duty Rosters, Menus/Recipes, links to various skills videos or resources, and the like. There are a lot of things briefly covered in official TLUSA publications that could use more depth and there are troops out there doing some really cool stuff that other troops would love to see.

With Trail Life's general policy of "you are the first line for getting information", I figure making that information easier to get isn't a bad idea.  BSA has had volunteers compiling all sorts of info for decades.  With TLUSA not being Scouting, a repo for something similar may be warranted.

But as noted - still trying to get a handle on this whole thing as a website. This was just me playing around - thus the separate account. And then trying to tie in Github's "use this as a website" with the underlying framework of static websites.  I usually do more Wordpress stuff just because it's a lot easier. 🙂
________________________________

**Comment by beingben** [comment]
I'm interested in where you go with this. I have a pretty handle on a few programming languages and have had the role of being a product manager in the past for SaaS services. I agree that what would be produced should not compete with TLC - perhaps it should eventually make its way into TLC. So having a clear purpose and approach will make the information collected useful and also be "future compatible"
Let me know if you would like to discuss more.
